### ISSUE TITLE
Contribute to Milestone 2 Group Report 

### ISSUE THREAD

**Issue by kataparuto** [bounswe/2021SpringGroup6#116]
- [x] Summary of the Project and Overall Status #115
- [x] Fill personal work table
- [x] Add the corresponding API functionality

**Comment by kataparuto** [comment]
[here](https://docs.google.com/document/d/e/2PACX-1vRn-pyDnwNdEm2hxbNq1u3qIu6Tjv9K0qpMGVAjg5H7Fs96SkKXqYL79uhckpe-ODPpWDQVyhym9m93/pub) is the link for the Milestone 2 Group documentation.

**Comment by kataparuto** [comment]
All the tasks are completed.
