### ISSUE TITLE
Contribute to the Milestone 2 Group Report

### ISSUE THREAD

**Issue by bnbcfyh** [bounswe/2021SpringGroup6#118]
- [x] Fill in the column of the table where every member's personal effort is briefly shown.
- [x] Add the information about the external public API that you used in your part in the app.
- [x] Add a description for your endpoint in the API documentation.
- [x] Add screenshots to show the front-end under your API documentation.
- [x] Review the other parts that are written by the other members of the team.

**Comment by fileames** [comment]
Thanks for your effort, since the report is done, and can be found [here](https://github.com/bounswe/2021SpringGroup6/blob/master/deliverables/M2_Report_Group6.pdf), we can close this issue.
