### ISSUE TITLE
Preperation for milestone presentation: fix styling

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#336]
Event settings page looks good but it could be better. 

- [x] Put map instead of random images
- [x] Set min width to event cards
- [x] Show real data instead of mocked one

**Comment by eye-78** [comment]
I did styling part in another branch #329 
The page now looks better
