### ISSUE TITLE
Combine Different Documents on Milestone Document

### ISSUE THREAD

**Issue by fileames** [bounswe/2021SpringGroup6#51]
Different documents will be combined on Milestone Document. Some of them will be taken from the Wiki and some will be added directly to the document.
Current phase of the document can be found [here](https://docs.google.com/document/d/e/2PACX-1vTzTLUga8ACwEdsyy36e-bO0V2AqMaalN2Ga193zEQh-eougckiPWZc5yWDprEp5cHJeXFBb13vqRJU/pub).

- [x] Executive Summary #47
- [x] List and status of deliverables. #49 
- [x] Evaluation of the status of deliverables and its impact on your project plan. 
- [x] Evaluation of tools and processes that you have used to manage your team project. #50
- [x]  A summary of work done by each team member (in tabular format) 
- [x] Deliverables 

   - [x] Communication plan

  - [x] Requirements

  - [x] Scenarios and Mockups
 
  - [x] Software design documents in UML

  - [x] Project plan 
 
  - [x] RAM (responsibility assignment matrix) #45

**Comment by fileames** [comment]
Final version which was submitted can be found [here](https://github.com/bounswe/2021SpringGroup6/blob/master/deliverables/M1-Group6.pdf).
