### ISSUE TITLE
Prepare Milestone 2 Structure (Group Part)

### ISSUE THREAD

**Issue by eye-78** [bounswe/2021SpringGroup6#98]
- [x] Build header hierarchy
- [x] Add summary
- [x] Add documentation for your part (api)
- [x] Describe functionality of the project
- [x] Comment on challenges faced
- [x] Contribute "Evaluation of Tools" part
- [x] Initialize individual work table

**Comment by eye-78** [comment]
- Built hierarchy using header numbers
- Initialized personal effort table. Sorted alphabetically

All other work can be found #126

**Comment by omersuve** [comment]
Thanks for your effort!

**Comment by fileames** [comment]
[Group Report](https://github.com/bounswe/2021SpringGroup6/blob/master/deliverables/M2_Report_Group6.pdf) is prepared. Thanks for your effort.
